---
swagger:
  version: 'v4.0.0'
  name: 'meowv.blog'
  title: 'meowv.blog api'
  description: 'Powered by .NET 5 on Linux'
  routePrefix: ''
  documentTitle: '🤣Api - 阿星Plus⭐⭐⭐'

sckey: 'SCU60393T5a94df1d5a9274125293f34a6acf928f5d78f551cf6d6'

storage:
  mongodb: 'mongodb://localhost/meowv_blog'
  redisIsEnabled: true
  redis: '127.0.0.1'

cors:
  policyName: 'meowv-policy'
  origins: 'https://*.meowv.com,https://localhost:44381,https://localhost:44382'

jwt:
  issuer: 'meowv_blog'
  audience: 'meowv_blog api'
  signingKey: 'H4sIAAAAAAAAA3N0cnZxdXP38PTy9vH18w8I9AkOCQ0Lj4iMAgDB4fXPGgAAAA'

worker:
  isEnabled: true
  cron: '0 0 0/1 * * ? *'

signature:
  path: 'D:\static\signature'
  urls:
  - url: 'https://api1.meowv.com'
    param: '1'
  - url: 'https://api2.meowv.com'
    param: '2'
  - url: 'https://api3.meowv.com'
    param: '3'

tencentCloud:
  secretId: 'AKIDlSrzZj0DXZKo0zslPnvmMfWdjYC6CG3d'
  secretKey: ''

authorize:
  github:
    clientId: 'e31df3ad90fb05adc29c'
    clientSecret: ''
    redirectUrl: 'https://admin.meowv.com/oauth/github'
    scope: 'user'
  gitee:
    clientId: '2aa9116886160b7a7d5d87f043df4f3331d15ac1b1f3b57844d87e0b7b62e9c2'
    clientSecret: ''
    redirectUrl: 'https://admin.meowv.com/oauth/gitee'
    scope: 'user_info emails'
  alipay:
    appId: '2021002125624107'
    redirectUrl: 'https://admin.meowv.com/oauth/alipay'
    scope: 'auth_user'
    privateKey: ''
    publicKey: ''
  dingtalk:
    appId: 'dingoakqr9viaxcysinlzh'
    appSecret: ''
    redirectUrl: 'https://admin.meowv.com/oauth/dingtalk'
    scope: 'snsapi_login'
  microsoft:
    clientId: 'b4c12337-8504-4da9-b85a-4961b7771426'
    clientSecret: ''
    redirectUrl: 'https://admin.meowv.com/oauth/microsoft'
    scope: 'user.read'
  weibo:
    clientId: '3725213942'
    clientSecret: ''
    redirectUrl: 'https://admin.meowv.com/oauth/weibo'
    scope: 'all'
  qq:
    clientId: '101935194'
    clientSecret: ''
    redirectUrl: 'https://admin.meowv.com/oauth/qq'
    scope: 'get_user_info'